language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  # GCC (even when clang is used)
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  # CMake
  - sudo apt-get install -qq cmake
  # Google Protobuf
  - sudo apt-get install -qq protobuf-compiler libprotobuf-dev
script:
  - mkdir build && cd build && cmake .. -G "Unix Makefiles" -DCMAKE_RULE_MESSAGES=OFF && make -j8
  - cd build/bin && ./test-roboime-core
