language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake
      - protobuf-compiler
      - libprotobuf-dev
      - libstdc++-4.8-dev
script:
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_RULE_MESSAGES=OFF
  - make -j8
  - cd bin
  - ./test-roboime-core
